### PR TITLE
Add: Open in MATLAB Online button

### PR DESCRIPTION
**Pull request by nothans**
This PR adds the new Open in MATLAB Online badge to the README.

PS.

I love this project. It is one of my favorites to add to my MATLAB session.

We released a new Open in MATLAB Online feature. Anyone can open this in MATLAB Online from GitHub and run the demo.

We just blogged about and highlighted your project! [Open science and reusable research with MATLAB Online and GitHub](https://blogs.mathworks.com/matlab/2023/07/20/open-science-and-reusable-research-with-matlab-online-and-github/)

### CODE REVIEW

**Comment by raacampbell** [comment]
Looks great!

**Comment by vijayiyer05** [comment]
Hi again @raacampbell 👋🏽

Unexpected but pleasantly so to see one of your contributions as an early adopter of the Open in MATLAB Online facility. 

While I'm looking, will just throw out a couple of suggestions for possible consideration:
- A live script version of the demo would be worth it because it can then be publicly viewed (with the outputs) via File Exchange (all live scripts appear on the Examples tab of the File Exchange entry)
- If you/one did such a refresh, one could replace subplot with the newer [tiled layout](https://www.mathworks.com/help/matlab/ref/tiledlayout.html)

**Comment by raacampbell** [comment]
Nice idea. The live script is really where this comes into its own. Will do it.

**Comment by nothans** [comment]
That's awesome. The Open in MATLAB Online button can now take advantage of the demo: [https://matlab.mathworks.com/open/github/v1?repo=raacampbell/shadedErrorBar&file=demo_shadedErrorBar.mlx](https://matlab.mathworks.com/open/github/v1?repo=raacampbell/shadedErrorBar&file=demo_shadedErrorBar.mlx)

If you tack on the file, then this will open automatically for your users.

Thank you!

**Comment by raacampbell** [comment]
Thanks, @nothans I updated the README.

**Comment by vijayiyer05** [comment]
Yay! The live script should propagate to File Exchange in ~24 hours at which point an Examples tab should show up. 

When it does, you'll actually have a link to it, which you might weave into the README as well. 

Your past colleague Dylan's [Brain Observatory Toolbox](https://github.com/emeyers/Brain-Observatory-Toolbox) illustrates this. There are links to both view on File Exchange (👀) & run on MATLAB Online (▶️), in that case for multiple examples. This lets folks look before they try.

Btw, projects to add publicly viewable & runnable examples to MATLAB community toolboxes are attractive ones for the community toolbox program. Would be glad to hear of any toolboxes you think could benefit from this treatment, now that you've learned the ropes (not too difficult!).

**Pull request merged**
